name             'java'
maintainer       'hfinucane'
maintainer_email 'hfinucane@solvco.com'
license          'Apache 2.0'
description      'Installs a jre from a mirror you provide'
version          '0.0.2'
